[package]
name = "audio_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
record-audio = {path="./record-audio"}
whisper-rs = "0.3.0"